import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PriceChart } from "@/components/price-chart";
import { getCryptoBundle, getCryptoRows } from "@/lib/tool-data";
import { formatCompact, formatPrice } from "@/lib/market-tools";
export const dynamic = "force-dynamic";
const aliases: Record<string, string> = { usdt: "tether", usdc: "usd-coin", dai: "dai", fdusd: "first-digital-usd", usde: "ethena-usde", pyusd: "paypal-usd" };
export async function generateMetadata({ params }: { params: Promise<{ pair: string }> }): Promise<Metadata> { const { pair } = await params; const title = pair.includes("-vs-") ? `${pair.toUpperCase().replace("-VS-", " vs ")} stablecoin comparison` : `${pair.toUpperCase()} peg history`; return { title, description: `${title} with current price, peg distance and market liquidity.`, alternates: { canonical: `/tools/stablecoins/${pair}` } }; }
export default async function StablecoinPage({ params }: { params: Promise<{ pair: string }> }) {
  const { pair } = await params; const symbols = pair.toLowerCase().split("-vs-").slice(0, 2);
  if (symbols.length === 1) { const bundle = await getCryptoBundle(aliases[symbols[0]] || symbols[0], 91); if (!bundle) notFound(); const prices = bundle.history.map((item: any) => Number(item.price)).filter(Number.isFinite).reverse(); const value = Number(bundle.price?.price); const delta = Number.isFinite(value) ? (value - 1) * 100 : null; return <main className="data-page tool-page"><div className="data-page-heading"><div><p className="eyebrow">PEG HISTORY</p><h1>{bundle.asset.symbol} stablecoin peg</h1><p>Current dollar-peg distance and recent stored price observations.</p></div><Link className="data-page-action" href="/tools/stablecoins">All stablecoins</Link></div><div className="tool-metrics"><div><span>Price</span><strong>{formatPrice(value)}</strong></div><div><span>Distance from $1</span><strong className={delta != null && Math.abs(delta) <= .1 ? "positive" : "negative"}>{delta == null ? "—" : `${delta >= 0 ? "+" : ""}${delta.toFixed(3)}%`}</strong></div><div><span>Market cap</span><strong>{formatCompact(Number(bundle.price?.marketCap))}</strong></div><div><span>Observations</span><strong>{prices.length}</strong></div></div><section className="asset-panel tool-chart"><h2>Recent peg history</h2><PriceChart values={prices}/></section><p className="data-footnote">Peg history is not proof of reserve quality, redemption access or issuer solvency.</p></main>; }
  const rows = await getCryptoRows(symbols.map((symbol) => aliases[symbol] || symbol));
  if (rows.length !== 2) notFound();
  return <main className="data-page tool-page"><div className="data-page-heading"><div><p className="eyebrow">STABLECOIN COMPARISON</p><h1>{rows.map(({ asset }) => asset.symbol).join(" vs ") || "Stablecoins not found"}</h1><p>Compare dollar-peg distance and market liquidity using the latest available prices.</p></div><Link className="data-page-action" href="/tools/stablecoins">View all stablecoins</Link></div><div className="comparison-grid">{rows.map(({ asset, price }) => { const current = Number(price?.price); const delta = Number.isFinite(current) ? (current - 1) * 100 : null; return <section className="asset-panel comparison-card" key={asset.slug}><p className="eyebrow">{asset.symbol}</p><h2><Link href={`/tools/stablecoins/${String(asset.symbol).toLowerCase()}` as any}>{asset.name}</Link></h2><strong className="comparison-price">{formatPrice(current)}</strong><dl className="fact-list"><div><dt>Distance from $1</dt><dd className={delta != null && Math.abs(delta) <= .1 ? "positive" : "negative"}>{delta == null ? "—" : `${delta >= 0 ? "+" : ""}${delta.toFixed(3)}%`}</dd></div><div><dt>Market cap</dt><dd>{formatCompact(Number(price?.marketCap))}</dd></div><div><dt>24h volume</dt><dd>{formatCompact(Number(price?.volume24h))}</dd></div></dl></section>; })}</div><p className="data-footnote">Price stability does not prove reserve quality or issuer solvency.</p></main>;
}
