import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getDatabase } from "@/lib/mongodb";
import { PriceChart } from "@/components/price-chart";
import { AffiliateCta } from "@/components/affiliate-cta";

export const revalidate = 3600;
type Props = { params: Promise<{ slug: string }> };
function money(value: unknown) { const n = Number(value); return value == null || !Number.isFinite(n) ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: n < 1 ? 8 : 2, notation: n >= 1_000_000 ? "compact" : "standard" }).format(n); }
async function load(slug: string) { const db = await getDatabase(); const asset = await db.collection("assets").findOne({ slug, type: "crypto", active: true }); if (!asset) return null; const assetId = `${asset.provider}:${asset.providerId}`; const [price, history, related] = await Promise.all([db.collection("latest_prices").findOne({ assetId }), db.collection("price_history").find({ assetId }).sort({ timestamp: -1 }).limit(30).toArray(), db.collection("assets").find({ type: "crypto", active: true, slug: { $ne: slug }, provider: { $ne: "polygon" } }, { projection: { slug: 1, symbol: 1, name: 1 } }).limit(6).toArray()]); return { asset, price, history, related }; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const result = await load((await params).slug); if (!result) return { title: "Crypto asset not found" }; const { asset, price } = result; const fullTitle = `${asset.name} (${asset.symbol}) Price`; const title = fullTitle.length > 48 ? `${asset.symbol} Price & Market Data` : fullTitle; return { title, description: `${asset.name} price is ${money(price?.price)}. View 24-hour change, market cap and recent history.`, alternates: { canonical: `/crypto/${asset.slug}` } }; }
export default async function CryptoDetailPage({ params }: Props) {
  const result = await load((await params).slug); if (!result) notFound(); const { asset, price, history, related } = result;
  const change = price?.change24h == null ? null : Number(price.change24h);
  const schema = { "@context": "https://schema.org", "@type": "FinancialProduct", name: asset.name, tickerSymbol: asset.symbol };
  return <main className="data-page asset-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="asset-breadcrumb"><Link href="/crypto">Crypto</Link><span>/</span>{asset.name}</div><div className="asset-top"><div><p className="eyebrow">Cryptocurrency</p><h1>{asset.name} <span>{asset.symbol}</span></h1><p>Price, market activity and recent history</p></div><Link className="data-page-action" href={`/convert/${asset.slug}`}>Convert {asset.symbol} to USD ↗</Link></div><div className="asset-price-line"><strong>{money(price?.price)}</strong><span className={change == null ? "muted" : change >= 0 ? "positive" : "negative"}>{change == null ? "—" : `${change >= 0 ? "+" : ""}${change.toFixed(2)}%`} <small>24h</small></span></div><div className="asset-grid"><section className="asset-main"><div className="asset-panel"><div className="asset-panel-heading"><h2>Price history</h2><span>Recent observations</span></div><PriceChart values={history.map((item) => Number(item.price)).reverse()} /></div><div className="asset-panel"><h2>About this market</h2><p>{asset.name} has a market capitalization of {money(price?.marketCap)} and 24-hour trading volume of {money(price?.volume24h)}. Prices can move quickly and may be delayed.</p><div className="asset-links"><Link href={`/convert/${asset.slug}`}>USD converter →</Link><Link href="/data-sources">About the data →</Link></div></div></section><aside className="asset-aside"><div className="asset-panel"><h2>Key figures</h2><dl className="fact-list"><div><dt>Market cap</dt><dd>{money(price?.marketCap)}</dd></div><div><dt>24h volume</dt><dd>{money(price?.volume24h)}</dd></div><div><dt>24h change</dt><dd className={change == null ? "muted" : change >= 0 ? "positive" : "negative"}>{change == null ? "—" : `${change >= 0 ? "+" : ""}${change.toFixed(2)}%`}</dd></div><div><dt>Last updated</dt><dd>{price?.updatedAt ? new Date(price.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }) + " UTC" : "—"}</dd></div></dl></div><div className="asset-panel"><h2>Explore more</h2><div className="asset-related">{related.map((item) => <Link key={item.slug} href={`/crypto/${item.slug}`}><strong>{item.name}</strong><span>{item.symbol} ↗</span></Link>)}</div></div></aside></div><AffiliateCta symbol={String(asset.symbol)} kind="crypto" /><p className="data-footnote">Market data is for reference and is not investment advice.</p></main>;
}
