import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getDatabase } from "@/lib/mongodb";
import { PriceChart } from "@/components/price-chart";

export const revalidate = 3600;
type Props = { params: Promise<{ symbol: string }> };
type Profile = { industry?: string; marketCap?: number; description?: string; primaryExchange?: string; website?: string };
async function load(symbol: string) { const db = await getDatabase(); const asset = await db.collection("assets").findOne({ provider: "polygon", symbol: symbol.toUpperCase(), active: true }); if (!asset) return null; const assetId = `polygon:${asset.providerId}`; const [price, history] = await Promise.all([db.collection("latest_prices").findOne({ assetId }), db.collection("price_history").find({ assetId }).sort({ timestamp: -1 }).limit(35).toArray()]); return { asset, price, history }; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const result = await load((await params).symbol); return result ? { title: `${result.asset.symbol} Stock Price`, description: `${result.asset.name} stock price, daily move and company information.`, alternates: { canonical: `/stocks/${String(result.asset.symbol).toLowerCase()}` } } : { title: "Stock not found" }; }
export default async function StockDetailPage({ params }: Props) {
  const result = await load((await params).symbol); if (!result) notFound(); const { asset, price, history } = result;
  const profile = (asset.profile || {}) as Profile; const change = price?.change24h == null ? null : Number(price.change24h);
  const schema = { "@context": "https://schema.org", "@type": "Corporation", name: asset.name, tickerSymbol: asset.symbol, url: `https://finance.blissbiovn.com/stocks/${String(asset.symbol).toLowerCase()}` };
  return <main className="data-page asset-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="asset-breadcrumb"><Link href="/stocks">US stocks</Link><span>/</span>{asset.name}</div><div className="asset-top"><div><p className="eyebrow">US stock · End-of-day</p><h1>{asset.name} <span>{asset.symbol}</span></h1><p>{profile.industry || "Company price and market information"}</p></div></div><div className="asset-price-line"><strong>{price?.price == null ? "—" : `$${Number(price.price).toFixed(2)}`}</strong><span className={change == null ? "muted" : change >= 0 ? "positive" : "negative"}>{change == null ? "—" : `${change >= 0 ? "+" : ""}${change.toFixed(2)}%`} <small>daily move</small></span></div><div className="asset-grid"><section className="asset-main"><div className="asset-panel"><div className="asset-panel-heading"><h2>Price history</h2><span>Recent trading days</span></div><PriceChart values={history.map((item) => Number(item.price)).reverse()} /></div><div className="asset-panel"><h2>About {asset.name}</h2><p>{profile.description || `Explore recent price and trading activity for ${asset.name}.`}</p>{profile.website && <a href={profile.website} rel="nofollow noopener" target="_blank">Company website ↗</a>}</div></section><aside className="asset-aside"><div className="asset-panel"><h2>Key figures</h2><dl className="fact-list"><div><dt>Last close</dt><dd>{price?.price == null ? "—" : `$${Number(price.price).toFixed(2)}`}</dd></div><div><dt>Market cap</dt><dd>{profile.marketCap ? `$${(profile.marketCap / 1_000_000_000).toFixed(1)}B` : "—"}</dd></div><div><dt>Volume</dt><dd>{price?.volume24h == null ? "—" : Number(price.volume24h).toLocaleString("en-US")}</dd></div><div><dt>Industry</dt><dd>{profile.industry || "—"}</dd></div><div><dt>Last updated</dt><dd>{price?.updatedAt ? new Date(price.updatedAt).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }) + " UTC" : "—"}</dd></div></dl></div><div className="asset-panel"><h2>Explore markets</h2><div className="asset-related"><Link href="/stocks"><strong>All US stocks</strong><span>↗</span></Link><Link href="/crypto"><strong>Cryptocurrency prices</strong><span>↗</span></Link></div></div></aside></div><p className="data-footnote">Prices are end-of-day and may be delayed. This information is not investment advice.</p></main>;
}
