import Link from "next/link";
import type { Metadata } from "next";
import { getCryptoRows } from "@/lib/tool-data";
import { formatCompact, formatPrice } from "@/lib/market-tools";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Stablecoin peg tracker", description: "Track major stablecoin prices and their distance from the one US dollar reference.", alternates: { canonical: "/tools/stablecoins" } };
const stablecoins = ["tether", "usd-coin", "dai", "first-digital-usd", "ethena-usde", "paypal-usd"];
export default async function StablecoinsPage() { const rows = await getCryptoRows(stablecoins); return <main className="data-page tool-page"><div className="data-page-heading"><div><p className="eyebrow">DECISION TOOL</p><h1>Stablecoin peg tracker</h1><p>Monitor the current distance from the one-dollar reference and compare market liquidity.</p></div></div><section className="data-table-card tool-table"><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Stablecoin</th><th>Price</th><th>Distance from $1</th><th>24h</th><th>Market cap</th></tr></thead><tbody>{rows.map(({ asset, price }) => { const value = Number(price?.price); const delta = Number.isFinite(value) ? (value - 1) * 100 : null; const move = price?.change24h == null ? null : Number(price.change24h); return <tr key={asset.slug}><td><Link className="asset-link" href={`/tools/stablecoins/${String(asset.symbol).toLowerCase()}` as any}><strong>{asset.name}</strong><small>{asset.symbol} · peg history</small></Link></td><td className="num">{formatPrice(value)}</td><td className={`num ${delta == null ? "muted" : Math.abs(delta) <= .1 ? "positive" : "negative"}`}>{delta == null ? "—" : `${delta >= 0 ? "+" : ""}${delta.toFixed(3)}%`}</td><td className={`num ${move == null ? "muted" : move >= 0 ? "positive" : "negative"}`}>{move == null ? "—" : `${move >= 0 ? "+" : ""}${move.toFixed(2)}%`}</td><td className="num">{formatCompact(Number(price?.marketCap))}</td></tr>; })}</tbody></table></div>{!rows.length && <p className="board-empty">Stablecoin data is not available yet.</p>}</section><p className="data-footnote">Peg distance is a price observation, not a measure of reserves, solvency or safety.</p></main>; }
